### PR TITLE
make it work with XCode 11 Beta 6

### PR DESCRIPTION
**Pull request by kevinabrioux**
Example App works again with XCode 11 Beta 6

Just add 

```
    public func send(subscription: Subscription) {
    }
```

That is required now https://developer.apple.com/documentation/combine/subject/3362858-send

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks Kevin! Can you confirm this is needed for the GM?

**Comment by kevinabrioux** [comment]
I don't understand what you means by GM 😄

**Comment by kevinabrioux** [comment]
So GM is for `Golden master`

i haven't tested yet on it. I will do it ASAP and comment and/or update this PR if needed !

**Comment by danielt1263** [comment]
Interesting trivia... The first three letters of the greek alphabet... α β ɣ (alpha, beta, gamma) are the three major releases of a software product. Over the years, "gamma" has transformed "gold master candidate", but for some reason "beta" and "alpha" haven't changed. :-)

**Comment by freak4pc** [comment]
Love it :)) I’m a fan of trivia

**Comment by freak4pc** [comment]
Fixed it [here](https://github.com/freak4pc/RxCombine/commit/8c682b99ffc5e8d62ced7ad84c7b2bf0b031d63d) with some other minor things. Thank you!

**Pull request closed without merging**
